name: CI Build Simulation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Make build script executable
        run: chmod +x fake_build.sh

      - name: Run CI build step
        run: python3 ci_step.py
